### PR TITLE
Subchapters (#36)

### LINKED ISSUE #36: Subchapters
More and more manga in my follows use subchapters not just for extras but to also split up the chapter intentionally.
There are a few things I don't like about MyMangaDex' handling of that, so I wanted to catch your input on that before potentially making another pull request.

- Reader:
The update dialog is always shown as failed and one has to manually click update.
I'd like to add an additional check to see if it's the same chapter but a subchapter, in which case I'd display a different updated popup and only save it in local storage (no need to send to MAL)

- Follows/Title page:
Higher subchapters are generally shown either all in 'next chapter' color (follows) or 'current chapter' (title, totally unacceptable for me).
I know that finding the next chapter is impossible, because there is no guarantee that 0.1 steps are used. But at least on the title page it is possible to simply choose the next one if you go through them from the bottom. On the follows page I would like to also follow that assumption, though it means trusting that the scans release them in order). An alternative would be to save subchapters for a second pass, which would be more reliable.

### PR DESCRIPTION
**Pull request by cpiber**
Reader updates if higher subchapter, request to MAL only if `realChapter != lastMyAnimeListChapter`
On title page simply select the one after the current chapter as next (and all with same chapter value)
When no chapter corresponding to `lastMangaDexChapter` is found, mark all subchapters as current one (assume was synced from MAL)
On chapter list move information collection to front and calculate next chapter

Did not detect any bugs, but might need more testing
Closes #36

### CODE REVIEW

File: scripts/myMangaDex.js [hunk 1]
```diff
@@ -163,9 +164,9 @@ class MyMangaDex {
 				}
 
 				let isNext = (realChapter < 0 ||
-					realChapter == this.manga.lastMyAnimeListChapter ||
-					(realChapter == this.manga.lastMyAnimeListChapter + 1 ||
-						(!this.options.saveOnlyHigher && realChapter == this.manga.lastMyAnimeListChapter - 1)));
+					//realChapter == this.manga.lastMyAnimeListChapter ||
```
Comment (cpiber) [inline scripts/myMangaDex.js:167]:
```suggestion
				realChapter == this.manga.lastMyAnimeListChapter ||
					(realChapter == this.manga.lastMyAnimeListChapter + 1 ||
						(!this.options.saveOnlyHigher && realChapter == this.manga.lastMyAnimeListChapter - 1)));
```
I don't think these belong but I thought I'd tell you I removed them, maybe there is a reason they're here

File: scripts/myMangaDex.js [hunk 2]
```diff
@@ -1493,14 +1535,7 @@ class MyMangaDex {
...
 		await this.fetchMyAnimeList();
-		// Save LocalStorage to MAL values if it's higher
-		if (this.manga.lastMyAnimeListChapter > this.manga.lastMangaDexChapter) {
-			this.manga.lastMangaDexChapter = this.manga.lastMyAnimeListChapter;
-			if (this.options.saveAllOpened) {
-				this.insertChapter(this.manga.lastMangaDexChapter);
-			}
-			await updateLocalStorage(this.manga, this.options);
-		}
+
```
Comment (cpiber) [inline scripts/myMangaDex.js:1538]:
```suggestion
		// Save LocalStorage to MAL values if it's higher
		if (this.manga.lastMyAnimeListChapter > this.manga.lastMangaDexChapter) {
			this.manga.lastMangaDexChapter = this.manga.lastMyAnimeListChapter;
			if (this.options.saveAllOpened) {
				this.insertChapter(this.manga.lastMangaDexChapter);
			}
			await updateLocalStorage(this.manga, this.options);
		}
```
I forgot to add this to the new reader and there were no problems, this block should not be needed

File: scripts/myMangaDex.js [hunk 3]
```diff
@@ -265,6 +269,7 @@ class MyMangaDex {
 			this.insertChapter(this.manga.currentChapter.chapter);
 		}
 		// Update local storage - after, it doesn't really matter
+		this.manga.lastMangaDexChapter = this.manga.currentChapter.chapter;
```
Comment (cpiber) [inline scripts/myMangaDex.js:272]: Never set the last chapter!

File: scripts/myMangaDex.js (hunk 1 above)
Comment (Glagan) [reply scripts/myMangaDex.js:167]: This was used to check if it was the next chapter, iirc, but this code is a mess :)

**Comment by Glagan** [comment]
I will try to do some tests before merging.

**Comment by Glagan** [comment]
With these options:
```
{
  "confirmChapter": true,
  "saveOnlyHigher": true,
  "saveOnlyNext": true
}
```
And last chapter as ``26.1`` in save, I get a confirmation dialog when reading chapter ``26.2`` (with this title https://mangadex.org/title/23811/boku-no-kokoro-no-yabai-yatsu)
Also happens when the saved chapter is ``27`` and I try to read ``27.1``

**Comment by cpiber** [comment]
My bad, didn't consider "saveOnlyNext". I now modified the check whether the current chapter is the next one to include all chapters that are higher than the current subchapter and less than or equal next chapter (so all remaining subchapters and those of the next bigger chapter fall into this).
If you don't like this being just a guess I think I can also save the chapter list (from update reader event) and compare there.

**Comment by Glagan** [comment]
Guessing is not a problem, you just made the range smaller compared to what I did before, you can't really know if it's the next one anyway.  
I think the chapter list is only of the group you are currently reading, so if you change group it might be incorrect (I don't think it's really common but still).

**Comment by cpiber** [comment]
I just checked. There is `chapterList` which is a merge of all chapters, current group if available (so other group is used if this one didn't post). Then there is `chapters` which holds all available chapters from all groups.
So if we trust that no subchapters are skipped, this might work, though personally I would use this as an additional check (still make sure that this is higher and could be the next chapter). But this way possible subchapter jumps could be detected

**Comment by cpiber** [comment]
Do you want me to change anything or did you find any more problems?
What do you think of implementing this change with the `chapterList`?

**Comment by Glagan** [comment]
Sorry I was banned for 24hours after testing things, I'm just making more tests myself with a different combination of options and I'll merge it when I'm done if I don't find any problems.

What do you mean with ``chapterList`` ? Didn't you already change the highlights check for next chapter and such ?

**Comment by Glagan** [comment]
I don't see any problems, everything seems good, I'll merge it if you don't have anything else to add.

**Comment by cpiber** [comment]
Sorry, was working on something else. I noticed that the `chapterupdate` event also provides access to a `chapterList` array that could be used to check if it really is the next uploaded chapter, but I haven't implemented this additional check, do you think I should or is it good enough as is?

**Comment by Glagan** [comment]
I think it's good as it is, but if you still want to implement it you can.

**Comment by cpiber** [comment]
Don't think it's necessary either
